done
EtherDaler/lolcode-iterpr pull request #1
Opened 2022-12-13 02:08 UTC by EtherDaler

2022-12-25 17:19 UTC, akhtyamovpavel requested changes
Добрый вечер!

Необходимо избавиться от однобуквенных переменных. Буду ждать обновленную версию кода!

2022-12-25 17:19 UTC, akhtyamovpavel commented on driver.cpp
> +    variables["two"] = 2;
Это нам зачем?

2022-12-25 17:19 UTC, akhtyamovpavel commented on ast.h
> +struct Operator {
1 базовый класс - 1 файл

2022-12-25 17:19 UTC, akhtyamovpavel commented on runtime.cpp
> +  if (i)
Фигурные скобки

2022-12-25 17:19 UTC, akhtyamovpavel commented on runtime.cpp
> +  delete s;
Кто такие i, f, s?

2022-12-25 17:19 UTC, akhtyamovpavel commented on runtime.cpp
> +    return v + *this;
Вы думаете, что этот код работает нормально?

2022-12-25 17:19 UTC, akhtyamovpavel commented on scanner.l
> +                n.replace(i, 2, ":");
Следите за табуляцией

2022-12-27 05:31 UTC, EtherDaler commented on runtime.cpp
> +    return v + *this;
Да, верно

2022-12-27 05:32 UTC, EtherDaler commented on runtime.cpp
> +  delete s;
поправил

2022-12-27 05:32 UTC, EtherDaler commented on runtime.cpp
> +  if (i)
поправил

2022-12-27 05:32 UTC, EtherDaler commented on ast.h
> +struct Operator {
точно, как я забыл про это

2022-12-27 05:32 UTC, EtherDaler commented on driver.cpp
> +    variables["two"] = 2;
ну просто в конструкторе задаю параметры по умолчанию

2022-12-27 05:36 UTC, EtherDaler commented on scanner.l
> +                n.replace(i, 2, ":");
пофиксил

2022-12-27 17:23 UTC, akhtyamovpavel approved these changes
Добрый вечер!

Доводите этот пример до ума. Сейчас за него могу поставить хор(7)

2022-12-27 17:23 UTC, merged